baseurl: ""
url: "https://freebogatov.xyz"

github: komachi/freebogatov.xyz
twitter:
  username: freeBogatov
og:
  type: article
logo: /images/freebogatov.jpg
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      seo:
        type: Article
      image: /images/freebogatov.jpg

languages:
  - name: English
    link: '/en'
    code: en_US
  - name: Русский
    link: '/'
    code: ru_RU


# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
