baseurl: ""
url: "https://imshara.github.io/freebelov/"

github: imShara/freevlasov.info
twitter:
  username: freeVlasov
og:
  type: article
logo: /images/freevlasov.jpg
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      seo:
        type: Article
      image: /images/freevlasov.jpg

languages:
  - name: Русский
    link: '/'
    code: ru_RU


# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
